/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kategoriBarang;

import Login.Login;
import com.tools.Koneksi;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author basisb01
 */
public class KategoriBarangForm extends javax.swing.JFrame {

    /**
     * Creates new form KategoriBarangFormm
     */
    public KategoriBarangForm() {
        initComponents();
        textKodeKategori.requestFocus();
        LihatKategori();
        tombolSimpan.setEnabled(false);
        tombolHapus.setEnabled(false);
        tombolUpdate.setEnabled(false);
    }

    private void LihatKategori() {
        try {
            List<KategoriBarang> daftarKategori = KategoriKontrol.getKoneksiKategori().lihatSeluruhKateogri();
            KategoriTableModel model = new KategoriTableModel(daftarKategori);
            tableKategoriBarang.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarangForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textKodeKategori = new javax.swing.JTextField();
        textNamaKategori = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tombolSimpan = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        tombolKeluar = new javax.swing.JButton();
        tombolUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKategoriBarang = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kategori Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Kode Kategori");

        jLabel3.setText("Nama Kategori");

        textKodeKategori.setToolTipText("Masukan Kode Kategori");
        textKodeKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodeKategoriActionPerformed(evt);
            }
        });
        textKodeKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textKodeKategoriKeyPressed(evt);
            }
        });

        textNamaKategori.setToolTipText("Masukna Nama Kategori");
        textNamaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaKategoriActionPerformed(evt);
            }
        });
        textNamaKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNamaKategoriKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textKodeKategori))
                .addGap(391, 391, 391))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textKodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(0, 50, 470, 90);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tombolSimpan.setMnemonic('s');
        tombolSimpan.setText("Simpan");
        tombolSimpan.setToolTipText("Simpan Data");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolBatal.setText("Batal");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        tombolKeluar.setText("Keluar");
        tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKeluarActionPerformed(evt);
            }
        });

        tombolUpdate.setText("Update");
        tombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tombolSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(tombolKeluar)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolHapus)
                    .addComponent(tombolBatal)
                    .addComponent(tombolKeluar)
                    .addComponent(tombolUpdate))
                .addGap(19, 19, 19))
        );

        jDesktopPane1.add(jPanel3);
        jPanel3.setBounds(0, 140, 470, 40);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tableKategoriBarang.setAutoCreateRowSorter(true);
        tableKategoriBarang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableKategoriBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Kategori", "Nama Kategori"
            }
        ));
        tableKategoriBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKategoriBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableKategoriBarang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.add(jPanel4);
        jPanel4.setBounds(0, 180, 470, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textKodeKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodeKategoriActionPerformed

        try {
            String kode = textKodeKategori.getText();
            if (kode.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "Barang Tidak Ditemukan");
            }
            String nama = KategoriKontrol.getKoneksiKategori().cariKategori(kode);
            textNamaKategori.setText(nama);
            tombolHapus.setEnabled(true);
        } catch (SQLException ex) {
            //Logger.getLogger(KategoriBarangForm.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error = " + ex.getMessage());
        }


    }//GEN-LAST:event_textKodeKategoriActionPerformed

    private void textNamaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaKategoriActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
//        JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin hapus data?");
//        if (JOptionPane.YES_OPTION)
        try {
            String key = textKodeKategori.getText();
            KategoriKontrol.getKoneksiKategori().HapusKategori(key);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Dihapus");
            textKodeKategori.requestFocus();
            LihatKategori();
            textKodeKategori.setText("");
            textNamaKategori.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        textKodeKategori.setText("");
        textNamaKategori.setText("");
        tombolSimpan.setText("Simpan");
        tombolSimpan.setEnabled(false);
        tombolHapus.setEnabled(false);
        tombolUpdate.setEnabled(false);
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void tombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_tombolKeluarActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        try {
            String kodeKategori = textKodeKategori.getText();
            String namaKategori = textNamaKategori.getText();
            KategoriBarang kategori = new KategoriBarang();
            kategori.setKodeKategori(kodeKategori);
            kategori.setNamaKategori(namaKategori);
            KategoriKontrol.getKoneksiKategori().tambahKategoriPrepared(kategori);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");
            textKodeKategori.requestFocus();
            LihatKategori();
            textKodeKategori.setText("");
            textNamaKategori.setText("");
            tombolSimpan.setEnabled(false);
            tombolHapus.setEnabled(false);

        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,
                    "Data Gagal Disimpan");
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tableKategoriBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKategoriBarangMouseClicked
        int baris = tableKategoriBarang.getSelectedRow();
        String kode = tableKategoriBarang.getValueAt(baris, 0).toString();
        String nama = tableKategoriBarang.getValueAt(baris, 1).toString();

        textKodeKategori.setText(kode);
        textNamaKategori.setText(nama);
        tombolUpdate.setEnabled(true);
        tombolSimpan.setEnabled(false);
        tombolHapus.setEnabled(true);

    }//GEN-LAST:event_tableKategoriBarangMouseClicked

    private void textNamaKategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNamaKategoriKeyPressed
        if (evt.getKeyCode() == 10) {
            textNamaKategori.requestFocus();
            tombolSimpan.setEnabled(true);
            
        }
    }//GEN-LAST:event_textNamaKategoriKeyPressed

    private void textKodeKategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKodeKategoriKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodeKategoriKeyPressed

    private void tombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUpdateActionPerformed
        try {
            String kodeKategori = textKodeKategori.getText();
            String namaKategori = textNamaKategori.getText();
            KategoriBarang kategori = new KategoriBarang();
            kategori.setKodeKategori(kodeKategori);
            kategori.setNamaKategori(namaKategori);
            KategoriKontrol.getKoneksiKategori().UpdateKategori(kodeKategori, namaKategori);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Diupdate");
            textKodeKategori.requestFocus();
            LihatKategori();
            textKodeKategori.setText("");
            textNamaKategori.setText("");
            tombolUpdate.setEnabled(false);
            tombolHapus.setEnabled(false);

        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,
                    "Data Gagal Diupdate");
        }
    }//GEN-LAST:event_tombolUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KategoriBarangForm().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableKategoriBarang;
    private javax.swing.JTextField textKodeKategori;
    private javax.swing.JTextField textNamaKategori;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKeluar;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUpdate;
    // End of variables declaration//GEN-END:variables
}
