/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.barang;

import com.kategoriBarang.KategoriBarang;
import com.kategoriBarang.KategoriKontrol;
import com.tools.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dion Wisnu
 */
public class BarangForm extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public BarangForm() {
        initComponents();
        lihatKategori();
        ButtonSimpan.setEnabled(false);
        ButtonHapus.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        InternalList = new javax.swing.JInternalFrame();
        PanelList = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListBarang = new javax.swing.JTable();
        buttonKeluarList = new javax.swing.JButton();
        buttonHapusList = new javax.swing.JButton();
        InternalCetak = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tfInKodeAwal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfInKodeAkhir = new javax.swing.JTextField();
        tfNamaBrgKodeAwal = new javax.swing.JTextField();
        tfNamaBrgKodeAkhir = new javax.swing.JTextField();
        cbPilihCetak = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableListCetak = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        buttonCetakGroup = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ButtonUpload = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfQtyMax = new javax.swing.JTextField();
        comboKategori = new javax.swing.JComboBox();
        comboSatuan = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        tfQtyMin = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        ButtonCetakDaftarMenu = new javax.swing.JButton();
        ButtonSimpan = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfRitelSetelahPpn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfRitelSebelumPpn = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfBeliSetelahPpn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfBeliSebelumPpn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(799, 642));

        InternalList.setTitle("Daftar Barang");
        InternalList.setVisible(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Data yang dicari");

        tfCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariDataActionPerformed(evt);
            }
        });
        tfCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariDataKeyReleased(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabelListBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori Barang", "Harga Jual"
            }
        ));
        tabelListBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListBarang);

        buttonKeluarList.setText("Keluar");
        buttonKeluarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarListActionPerformed(evt);
            }
        });

        buttonHapusList.setText("Hapus");
        buttonHapusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListLayout = new javax.swing.GroupLayout(PanelList);
        PanelList.setLayout(PanelListLayout);
        PanelListLayout.setHorizontalGroup(
            PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListLayout.createSequentialGroup()
                .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonHapusList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKeluarList))
                    .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelListLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(tfCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelListLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelListLayout.setVerticalGroup(
            PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKeluarList)
                    .addComponent(buttonHapusList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InternalListLayout = new javax.swing.GroupLayout(InternalList.getContentPane());
        InternalList.getContentPane().setLayout(InternalListLayout);
        InternalListLayout.setHorizontalGroup(
            InternalListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        InternalListLayout.setVerticalGroup(
            InternalListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPane1.add(InternalList);
        InternalList.setBounds(0, 0, 530, 285);

        InternalCetak.setTitle("Cetak Data");
        InternalCetak.setVisible(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("CETAK DAFTAR");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Kode Awal");

        tfInKodeAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfInKodeAwalKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Kode Akhir");

        cbPilihCetak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cetak Semua Data", "Cetak Beberapa Data" }));
        cbPilihCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihCetakActionPerformed(evt);
            }
        });

        jLabel23.setText("Pilihan Cetak :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbPilihCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfInKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInKodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNamaBrgKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamaBrgKodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfInKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamaBrgKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPilihCetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tfInKodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaBrgKodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        tableListCetak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Beli", "Harga Jual"
            }
        ));
        jScrollPane2.setViewportView(tableListCetak);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        buttonCetakGroup.setText("Cetak");
        buttonCetakGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakGroupActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonCetakGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(67, 67, 67))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCetakGroup)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InternalCetakLayout = new javax.swing.GroupLayout(InternalCetak.getContentPane());
        InternalCetak.getContentPane().setLayout(InternalCetakLayout);
        InternalCetakLayout.setHorizontalGroup(
            InternalCetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InternalCetakLayout.setVerticalGroup(
            InternalCetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalCetakLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.add(InternalCetak);
        InternalCetak.setBounds(0, 0, 573, 411);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(599, 640));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Barang");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Digunakan untuk menambah, mengedit, menghapus dan mencari daftar barang.");

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Project Kuliah\\Semester 5\\Praktikum\\Praktikum Aplikasi Basis Data\\Aplikasi BasisData\\icon\\logo Toko trans.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Barang");

        tfNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNamaBarangKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kategori Barang");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Satuan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kode Barang");

        tfKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeBarangActionPerformed(evt);
            }
        });
        tfKodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKodeBarangKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Foto Produk");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Foto");
        jLabel9.setToolTipText("");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonUpload.setText("upload");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Qty. Max");

        tfQtyMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfQtyMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtyMaxActionPerformed(evt);
            }
        });
        tfQtyMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQtyMaxKeyTyped(evt);
            }
        });

        comboKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboKategoriMouseClicked(evt);
            }
        });
        comboKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKategoriActionPerformed(evt);
            }
        });

        comboSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "buah", "pack", "lusin" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Qty. Min");

        tfQtyMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfQtyMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtyMinActionPerformed(evt);
            }
        });
        tfQtyMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQtyMinKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfKodeBarang)
                            .addComponent(comboKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboSatuan, 0, 195, Short.MAX_VALUE)
                            .addComponent(tfQtyMax)
                            .addComponent(tfQtyMin))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(ButtonUpload)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(comboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(comboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(tfQtyMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tfQtyMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonUpload)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 80));

        ButtonCetakDaftarMenu.setText("Cetak Daftar Menu");
        ButtonCetakDaftarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCetakDaftarMenuActionPerformed(evt);
            }
        });

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonList.setText("List");
        ButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListActionPerformed(evt);
            }
        });

        ButtonBatal.setText("Batal");
        ButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatalActionPerformed(evt);
            }
        });

        ButtonKeluar.setText("Keluar");
        ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ButtonCetakDaftarMenu)
                .addGap(18, 18, 18)
                .addComponent(ButtonSimpan)
                .addGap(18, 18, 18)
                .addComponent(ButtonHapus)
                .addGap(18, 18, 18)
                .addComponent(ButtonList)
                .addGap(18, 18, 18)
                .addComponent(ButtonBatal)
                .addGap(64, 64, 64)
                .addComponent(ButtonKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCetakDaftarMenu)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonList)
                    .addComponent(ButtonBatal)
                    .addComponent(ButtonKeluar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Informasi Penjualan");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Ritel Setelah PPN");

        tfRitelSetelahPpn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfRitelSetelahPpn.setText("0");
        tfRitelSetelahPpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRitelSetelahPpnActionPerformed(evt);
            }
        });
        tfRitelSetelahPpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRitelSetelahPpnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRitelSetelahPpnKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Ritel Sebelum PPN");

        tfRitelSebelumPpn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfRitelSebelumPpn.setText("0");
        tfRitelSebelumPpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRitelSebelumPpnActionPerformed(evt);
            }
        });
        tfRitelSebelumPpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRitelSebelumPpnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRitelSebelumPpnKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfRitelSetelahPpn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfRitelSebelumPpn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfRitelSetelahPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfRitelSebelumPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Informasi Pembelian");

        jPanel7.setPreferredSize(new java.awt.Dimension(867, 60));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Beli Setelah PPN");

        tfBeliSetelahPpn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfBeliSetelahPpn.setText("0");
        tfBeliSetelahPpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeliSetelahPpnActionPerformed(evt);
            }
        });
        tfBeliSetelahPpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBeliSetelahPpnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBeliSetelahPpnKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Beli Sebelum PPN");

        tfBeliSebelumPpn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfBeliSebelumPpn.setText("0");
        tfBeliSebelumPpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeliSebelumPpnActionPerformed(evt);
            }
        });
        tfBeliSebelumPpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBeliSebelumPpnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBeliSebelumPpnKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBeliSetelahPpn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBeliSebelumPpn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfBeliSetelahPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfBeliSebelumPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 599, 640);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        try {
            String kodeBrg = tfKodeBarang.getText();
            String namaBrg = tfNamaBarang.getText();
            String kategoriBrg = comboKategori.getSelectedItem().toString().substring(4);
            String satuanBrg = comboSatuan.getSelectedItem().toString();
            String qtyMax = tfQtyMax.getText();
            String qtyMin = tfQtyMin.getText();
            String ritelStlhPpn = tfRitelSetelahPpn.getText().replace(".", "");
            String ritelSblmPpn = tfRitelSebelumPpn.getText().replace(".", "");
            String beliStlhPpn = tfBeliSetelahPpn.getText().replace(".", "");
            String beliSblmPpn = tfBeliSebelumPpn.getText().replace(".", "");

            Barang brg = new Barang();
            KategoriBarang katBrg = new KategoriBarang();
            brg.setKodeBarang(kodeBrg);
            brg.setNamaBarang(namaBrg);
            katBrg.setNamaKategori(kategoriBrg);
            brg.setKategori(katBrg);
            brg.setSatuan(satuanBrg);
            brg.setQtyMax(qtyMax);
            brg.setQtyMin(qtyMin);
            brg.setRitelSetelahPpn(ritelStlhPpn);
            brg.setRitelSebelumPpn(ritelSblmPpn);
            brg.setBeliSebelumPpn(beliSblmPpn);
            brg.setBeliSetelahPpn(beliStlhPpn);
            BarangControl.getKoneksiKategori().tambahBarangPrepared(brg);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");
        } catch (SQLException ex) {
            System.out.println("Error = " + ex.getMessage());
        }
        tfBeliSebelumPpn.setText("0");
        tfBeliSetelahPpn.setText("0");
        tfKodeBarang.setText("");
        tfNamaBarang.setText("");
        tfQtyMax.setText("");
        tfQtyMin.setText("");
        tfRitelSebelumPpn.setText("0");
        tfRitelSetelahPpn.setText("0");
        ButtonSimpan.setEnabled(false);
        ButtonHapus.setEnabled(false);
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void tfQtyMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtyMaxKeyTyped
        char KeyChar = evt.getKeyChar();
        if (!((KeyChar >= '0') && (KeyChar <= '9') || (KeyChar == (char) 8) || (KeyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_tfQtyMaxKeyTyped

    private void ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonKeluarActionPerformed

    private void tfQtyMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtyMinKeyTyped
        char KeyChar = evt.getKeyChar();
        if (!((KeyChar >= '0') && (KeyChar <= '9') || (KeyChar == (char) 8) || (KeyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_tfQtyMinKeyTyped

    private void tfRitelSetelahPpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRitelSetelahPpnKeyTyped
        char karakter = evt.getKeyChar();
        if ((karakter >= '0') && (karakter <= '9')
                || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_tfRitelSetelahPpnKeyTyped

    private void tfRitelSebelumPpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRitelSebelumPpnKeyTyped
        char karakter = evt.getKeyChar();
        if ((karakter >= '0') && (karakter <= '9')
                || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_tfRitelSebelumPpnKeyTyped

    private void tfBeliSetelahPpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeliSetelahPpnKeyTyped
        char KeyChar = evt.getKeyChar();
        if (!((KeyChar >= '0') && (KeyChar <= '9') || (KeyChar == (char) 8) || (KeyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_tfBeliSetelahPpnKeyTyped

    private void tfBeliSebelumPpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeliSebelumPpnKeyTyped
        char KeyChar = evt.getKeyChar();
        if (!((KeyChar >= '0') && (KeyChar <= '9') || (KeyChar == (char) 8) || (KeyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_tfBeliSebelumPpnKeyTyped

    private void tfRitelSetelahPpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRitelSetelahPpnKeyReleased
        try {
            String a;
            Double temp;
            a = tfRitelSetelahPpn.getText();
            if (a.isEmpty()) {
                a = "0";
                tfRitelSebelumPpn.setText("0");
            } else {
                String ppnSblm = tfRitelSetelahPpn.getText();
                int hargasebelum = Integer.parseInt(((ppnSblm).replace(".", "")));
                int hsetelah = hargasebelum * 10 / 11;
                tfRitelSebelumPpn.setText(String.valueOf(hsetelah));
                a = a.replaceAll("\\.", "");
                a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Integer.parseInt(a));
                a = a.replaceAll(",", ".");
            }
            tfRitelSetelahPpn.setText(a);
        } catch (NumberFormatException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_tfRitelSetelahPpnKeyReleased

    private void tfRitelSebelumPpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRitelSebelumPpnKeyReleased
        try {
            String a;
            int temp;
            a = tfRitelSebelumPpn.getText();
            if (a.isEmpty()) {
                a = "0";
                tfRitelSetelahPpn.setText("0");
            } else {
                String ppnSblm = tfRitelSebelumPpn.getText();
                int hargasebelum = Integer.parseInt((ppnSblm).replace(".", ""));
                int hsetelah = hargasebelum * 11 / 10;
                tfRitelSetelahPpn.setText(String.valueOf(hsetelah));
                a = a.replaceAll("\\.", "");
                a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Integer.parseInt(a));
                a = a.replaceAll(",", ".");
            }
            tfRitelSebelumPpn.setText(a);
        } catch (NumberFormatException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_tfRitelSebelumPpnKeyReleased

    private void tfBeliSetelahPpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeliSetelahPpnKeyReleased
        String a;
        int temp;
        a = tfBeliSetelahPpn.getText();
        if (a.isEmpty()) {
            a = "0";
            tfBeliSebelumPpn.setText("0");
        } else {
            String beliStlh = tfBeliSetelahPpn.getText();
            int hargasetelah = Integer.parseInt((beliStlh).replace(".", ""));
            int hseblm = hargasetelah * 10 / 11;
            tfBeliSebelumPpn.setText(String.valueOf(hseblm));
            a = a.replaceAll("\\.", "");
            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Integer.parseInt(a));
            a = a.replaceAll(",", ".");
        }
        tfBeliSetelahPpn.setText(a);
    }//GEN-LAST:event_tfBeliSetelahPpnKeyReleased

    private void tfBeliSebelumPpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBeliSebelumPpnKeyReleased
        String a;
        int temp;
        a = tfBeliSebelumPpn.getText();
        if (a.isEmpty()) {
            a = "0";
            tfBeliSetelahPpn.setText("0");
        } else {
            String beliSblm = tfBeliSebelumPpn.getText();
            int hargasebelum = Integer.parseInt((beliSblm).replace(".", ""));
            int hsetelah = hargasebelum * 11 / 10;
            tfBeliSetelahPpn.setText(String.valueOf(hsetelah));

            a = a.replaceAll("\\.", "");
            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Integer.parseInt(a));
            a = a.replaceAll(",", ".");
        }
        tfBeliSebelumPpn.setText(a);
    }//GEN-LAST:event_tfBeliSebelumPpnKeyReleased

    private void tfRitelSetelahPpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRitelSetelahPpnActionPerformed
//        if (tfRitelSetelahPpn.getText().equalsIgnoreCase("")) {
//            tfRitelSebelumPpn.setText("0");
//        } else {
//            String ppnStlh = tfRitelSetelahPpn.getText();
//            Double hargasetelah = Double.parseDouble((ppnStlh).replace(".", ""));
//            Double hseblm = hargasetelah * 10 / 11;
//            tfRitelSebelumPpn.setText(hseblm.toString());
//        }
    }//GEN-LAST:event_tfRitelSetelahPpnActionPerformed

    private void tfRitelSebelumPpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRitelSebelumPpnActionPerformed
//
//        if (tfRitelSebelumPpn.getText().equalsIgnoreCase("")) {
//            tfRitelSetelahPpn.setText("0");
//        } else {
//            String ppnSblm = tfRitelSebelumPpn.getText();
//            Double hargasebelum = Double.parseDouble((ppnSblm).replace(".", ""));
//            Double hsetelah = hargasebelum * 11 / 10;
//            tfRitelSetelahPpn.setText(hsetelah.toString());
//
//        }
    }//GEN-LAST:event_tfRitelSebelumPpnActionPerformed

    private void ButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListActionPerformed
        InternalList.setVisible(true);
        LihatListBarang(tabelListBarang);
    }//GEN-LAST:event_ButtonListActionPerformed

    private void tfQtyMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtyMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtyMaxActionPerformed

    private void tfQtyMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtyMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtyMinActionPerformed

    private void buttonKeluarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarListActionPerformed
        InternalList.setVisible(false);
    }//GEN-LAST:event_buttonKeluarListActionPerformed

    private void comboKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKategoriActionPerformed
        String substring = null;
        try {
            substring = comboKategori.getSelectedItem().toString().trim().substring(0, 3);
        } catch (NullPointerException ex) {

        }
        String kodeBaru = Barang.cariMaxKode(substring);
        tfKodeBarang.setText(kodeBaru);
//        try {
//            KategoriBarang kb = new KategoriBarang();
//            kb.setKodeKategori(comboKategori.getSelectedItem().toString().substring(0, 4).trim());
//            tfKodeBarang.setText(KategoriKontrol.getKoneksiKategori().getKodeKategori(kb)
//                    + KategoriKontrol.getKoneksiKategori().cariKode(kb) + "");
//        } catch (SQLException ex) {
//            System.out.println("Error : " + ex.getMessage());
//        }
//        String isi = comboKategori.getSelectedItem().toString();
//        tfKodeBarang.setText(isi);
    }//GEN-LAST:event_comboKategoriActionPerformed

    private void tfBeliSetelahPpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeliSetelahPpnActionPerformed
//        if (tfBeliSetelahPpn.getText().equalsIgnoreCase("")) {
//            tfBeliSebelumPpn.setText("0");
//        } else {
//            String beliStlh = tfBeliSetelahPpn.getText();
//            Double hargasetelah = Double.parseDouble((beliStlh).replace(".", ""));
//            Double hseblm = hargasetelah * 10 / 11;
//            tfBeliSebelumPpn.setText(hseblm.toString());
//        }
    }//GEN-LAST:event_tfBeliSetelahPpnActionPerformed

    private void tfBeliSebelumPpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeliSebelumPpnActionPerformed
//        if (tfBeliSebelumPpn.getText().equalsIgnoreCase("")) {
//            tfBeliSetelahPpn.setText("0");
//        } else {
//            String beliSblm = tfBeliSebelumPpn.getText();
//            Double hargasebelum = Double.parseDouble((beliSblm).replace(".", ""));
//            Double hsetelah = hargasebelum * 11 / 10;
//            tfBeliSetelahPpn.setText(hsetelah.toString());
//        }
//        ButtonSimpan.setEnabled(true);
    }//GEN-LAST:event_tfBeliSebelumPpnActionPerformed

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        tfBeliSebelumPpn.setText("0");
        tfBeliSetelahPpn.setText("0");
        tfKodeBarang.setText("");
        tfNamaBarang.setText("");
        tfQtyMax.setText("");
        tfQtyMin.setText("");
        tfRitelSebelumPpn.setText("0");
        tfRitelSetelahPpn.setText("0");
        ButtonSimpan.setEnabled(false);
        ButtonHapus.setEnabled(false);
    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void buttonCetakGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakGroupActionPerformed
        // TODO add your handling code here:
        Connection kon = null;
        String reportSource = "";
        String kodeAwal = tfInKodeAwal.getText();
        String kodeAkhir = tfInKodeAkhir.getText();
        try {
            kon = new Koneksi().getDBConnection();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        if (cbPilihCetak.getSelectedItem().equals("Cetak Semua Data")) {
            reportSource = "./Laporan/Laporan.jasper";
        } else if (cbPilihCetak.getSelectedItem().equals("Cetak Beberapa Data")) {
            reportSource = "./Laporan/LaporanDenganParameter.jasper";
        }
        Map<String, Object> params = new HashMap<String, Object>();
        params.put(kodeAwal, kodeAwal);
        params.put(kodeAkhir, kodeAkhir);
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, kon);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_buttonCetakGroupActionPerformed

    private void ButtonCetakDaftarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCetakDaftarMenuActionPerformed
        InternalCetak.setVisible(true);
        LihatListBarang(tableListCetak);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        tfInKodeAkhir.setVisible(false);
        tfInKodeAwal.setVisible(false);
        tfNamaBrgKodeAwal.setVisible(false);
        tfNamaBrgKodeAkhir.setVisible(false);
//        Connection kon = null;
//        String reportSource = "";
//        try {
//            kon = new Koneksi().getDBConnection();
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//        reportSource = "./Laporan/Laporan.jasper";
//
//        Map<String, Object> params = new HashMap<String, Object>();
//        try {
//            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, kon);
//            JasperViewer.viewReport(jasperPrint, false);
//        } catch (JRException ex) {
//            ex.printStackTrace();
//        }

    }//GEN-LAST:event_ButtonCetakDaftarMenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        InternalCetak.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaBarangKeyReleased
        if (tfNamaBarang.getText().equals("")) {
            ButtonSimpan.setEnabled(false);
        } else {
            ButtonSimpan.setEnabled(true);
        }

    }//GEN-LAST:event_tfNamaBarangKeyReleased

    private void tfKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeBarangActionPerformed

    private void buttonHapusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusListActionPerformed
        int baris = tabelListBarang.getSelectedRow();
        String kode = tabelListBarang.getValueAt(baris, 0).toString();

        try {
            BarangControl.getKoneksiKategori().HapusKategori(kode);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Dihapus");
            LihatListBarang(tabelListBarang);

        } catch (SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonHapusListActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabelListBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListBarangMouseClicked

    }//GEN-LAST:event_tabelListBarangMouseClicked

    private void tfCariDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariDataKeyReleased
//        String cari = tfCariData.getText();
//        try {
//            List<Barang> listCari = BarangControl.getKoneksiKategori().cariBarang(cari);
//            BarangTableModel model = new BarangTableModel(listCari);
//            tabelListBarang.setModel(model);
//            //LihatListBarang();
//        } catch (SQLException ex) {
//            System.out.println("Error : " + ex.getMessage());
//        }
    }//GEN-LAST:event_tfCariDataKeyReleased

    private void tfCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariDataActionPerformed
        String cari = tfCariData.getText();
        try {
            List<Barang> listCari = BarangControl.getKoneksiKategori().cariBarang(cari);
            BarangTableModel model = new BarangTableModel(listCari);
            tabelListBarang.setModel(model);

        } catch (SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_tfCariDataActionPerformed

    private void tfKodeBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKodeBarangKeyPressed
        // TODO add your handling code here:
        if (tfKodeBarang.getText().toCharArray().length >= 4) {
            String s = tfKodeBarang.getText().substring(0, 3);
            getToolkit().beep();
            tfKodeBarang.setText(s);
        }
    }//GEN-LAST:event_tfKodeBarangKeyPressed

    private void tfInKodeAwalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInKodeAwalKeyTyped
        // TODO add your handling code here:
        tfInKodeAwal.getText();
    }//GEN-LAST:event_tfInKodeAwalKeyTyped

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void cbPilihCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihCetakActionPerformed
        if (cbPilihCetak.getSelectedItem().equals("Cetak Semua Data")) {
            jLabel21.setVisible(false);
            jLabel22.setVisible(false);
            tfInKodeAkhir.setVisible(false);
            tfInKodeAwal.setVisible(false);
            tfNamaBrgKodeAwal.setVisible(false);
            tfNamaBrgKodeAkhir.setVisible(false);
        } else {
            jLabel21.setVisible(true);
            jLabel22.setVisible(true);
            tfInKodeAkhir.setVisible(true);
            tfInKodeAwal.setVisible(true);
            tfNamaBrgKodeAwal.setVisible(true);
            tfNamaBrgKodeAkhir.setVisible(true);
        }
    }//GEN-LAST:event_cbPilihCetakActionPerformed

    private void comboKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboKategoriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKategoriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BarangForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonCetakDaftarMenu;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKeluar;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JInternalFrame InternalCetak;
    private javax.swing.JInternalFrame InternalList;
    private javax.swing.JPanel PanelList;
    private javax.swing.JButton buttonCetakGroup;
    private javax.swing.JButton buttonHapusList;
    private javax.swing.JButton buttonKeluarList;
    private javax.swing.JComboBox cbPilihCetak;
    private javax.swing.JComboBox comboKategori;
    private javax.swing.JComboBox comboSatuan;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelListBarang;
    private javax.swing.JTable tableListCetak;
    private javax.swing.JTextField tfBeliSebelumPpn;
    private javax.swing.JTextField tfBeliSetelahPpn;
    private javax.swing.JTextField tfCariData;
    private javax.swing.JTextField tfInKodeAkhir;
    private javax.swing.JTextField tfInKodeAwal;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaBrgKodeAkhir;
    private javax.swing.JTextField tfNamaBrgKodeAwal;
    private javax.swing.JTextField tfQtyMax;
    private javax.swing.JTextField tfQtyMin;
    private javax.swing.JTextField tfRitelSebelumPpn;
    private javax.swing.JTextField tfRitelSetelahPpn;
    // End of variables declaration//GEN-END:variables

    private void LihatListBarang(JTable namaTable) {
        try {
            List<Barang> listBarang = BarangControl.getKoneksiKategori().lihatSeluruhBarang();
            BarangTableModel model = new BarangTableModel(listBarang);
            namaTable.setModel(model);
            System.out.println("List Berhasil");
        } catch (SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }

    private void lihatKategori() {
        comboKategori.removeAllItems();
        try {
            List<KategoriBarang> daftarKategori = KategoriKontrol.getKoneksiKategori().lihatSeluruhKateogri();
            for (int i = 0; i < daftarKategori.size(); i++) {
                KategoriBarang kategoriBarang = daftarKategori.get(i);
                comboKategori.addItem(kategoriBarang.getKodeKategori() + " " + kategoriBarang.getNamaKategori());

            }
        } catch (SQLException ex) {
            Logger.getLogger(BarangForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
